Repository kimjaewoo2233/STUDY-GROUP-ACTIVITY, pull requests merged in 2023-02, with the labels that each got.

#13 FEAT: 회원가입 그리고 회원가입에 들어오는 데이터 VALID추가
  back/build.gradle
  back/src/main/java/org/hotel/back/config/SecurityConfig.java
  back/src/main/java/org/hotel/back/controller/MemberController.java
  back/src/main/java/org/hotel/back/data/request/RegisterData.java
  back/src/main/java/org/hotel/back/domain/MemberRole.java
  back/src/main/java/org/hotel/back/repository/MemberRepository.java
  back/src/main/java/org/hotel/back/service/MemberService.java
  back/src/main/resources/templates/register.html
  back/src/main/resources/templates/test.html
Labels: Feat

#15 FEAT: 로그인 구현 그리고 회원가입때 중복체크 JS까지 구현
  back/src/main/java/org/hotel/back/config/SecurityConfig.java
  back/src/main/java/org/hotel/back/controller/MemberController.java
  back/src/main/java/org/hotel/back/controller/MemberDataController.java
  back/src/main/java/org/hotel/back/data/dto/MemberDTO.java
  back/src/main/java/org/hotel/back/domain/Gender.java
  back/src/main/java/org/hotel/back/domain/Member.java
  back/src/main/java/org/hotel/back/domain/MemberRole.java
  back/src/main/java/org/hotel/back/repository/MemberRepository.java
  back/src/main/java/org/hotel/back/service/MemberService.java
  back/src/main/java/org/hotel/back/service/api/HotelAPIService.java
  back/src/main/java/org/hotel/back/service/security/MemberDetailsService.java
  back/src/main/resources/templates/login.html
  back/src/main/resources/templates/register.html
  back/src/test/java/org/hotel/back/repository/MemberRepositoryTest.java
  back/src/test/java/org/hotel/back/service/security/MemberDetailsServiceTest.java
Labels: Feat

#17 MODIFIED: Login기능 추가작업
  back/src/main/java/org/hotel/back/config/SecurityConfig.java
  back/src/main/java/org/hotel/back/controller/MemberDataController.java
  back/src/main/java/org/hotel/back/data/dto/MemberDTO.java
  back/src/main/java/org/hotel/back/service/security/MemberDetailsService.java
  back/src/main/resources/templates/login.html
  back/src/main/resources/templates/register.html
  back/src/test/java/org/hotel/back/service/security/MemberDetailsServiceTest.java
Labels: bug

#19 FEAT:
  back/src/main/java/org/hotel/back/data/response/KaKaoResponseData.java
  back/src/main/java/org/hotel/back/service/api/HotelAPIService.java
  back/src/main/java/org/hotel/back/service/api/KaKaoAPIService.java
  back/src/main/resources/application.properties
  back/src/test/java/org/hotel/back/service/api/KaKaoAPIServiceTest.java
Labels: Feat

#23 FEAT: 객실 이미지와 함께 저장하는 기능 생성 아직 업데이트 삭제 못함
  back/src/main/java/org/hotel/back/config/exception/FileUploadException.java
  back/src/main/java/org/hotel/back/config/exception/FileViewException.java
  back/src/main/java/org/hotel/back/controller/RoomController.java
  back/src/main/java/org/hotel/back/controller/RoomImageController.java
  back/src/main/java/org/hotel/back/data/dto/FileDTO.java
  back/src/main/java/org/hotel/back/data/dto/UploadDTO.java
  back/src/main/java/org/hotel/back/data/response/FileResponseData.java
  back/src/main/java/org/hotel/back/data/response/RoomDTO.java
  back/src/main/java/org/hotel/back/domain/Booking.java
  back/src/main/java/org/hotel/back/domain/Hotel.java
  back/src/main/java/org/hotel/back/domain/Room.java
  back/src/main/java/org/hotel/back/domain/RoomImage.java
  back/src/main/java/org/hotel/back/repository/RoomRepository.java
  back/src/main/java/org/hotel/back/service/Impl/HotelServiceImpl.java
  back/src/main/java/org/hotel/back/service/Impl/RoomServiceImpl.java
  back/src/main/java/org/hotel/back/service/RoomService.java
  back/src/main/resources/application.properties
  back/src/main/resources/templates/room/room-save.html
Labels: feature

#24 FEAT: 이미지를 저장하는 기능 성공
  back/src/main/java/org/hotel/back/controller/RoomController.java
  back/src/main/java/org/hotel/back/controller/RoomImageController.java
  back/src/main/java/org/hotel/back/data/dto/FileDTO.java
  back/src/main/java/org/hotel/back/data/request/BookingRequestDTO.java
  back/src/main/java/org/hotel/back/data/response/BookingResponseDTO.java
  back/src/main/java/org/hotel/back/data/response/RoomDTO.java
  back/src/main/java/org/hotel/back/domain/Hotel.java
  back/src/main/java/org/hotel/back/domain/HotelImage.java
  back/src/main/java/org/hotel/back/domain/RoomImage.java
  back/src/main/java/org/hotel/back/service/Impl/BookingServiceImpl.java
  back/src/main/java/org/hotel/back/service/Impl/RoomServiceImpl.java
  back/src/main/resources/application.properties
  back/src/main/resources/templates/room/room-save.html
  back/temp/a19b3ac3-88f6-4715-baf2-9e1c95f8c955_외계인.jpg
  back/temp/c75cccf3-0cc1-4f60-80eb-196862b09896_엑시트.jpg
  back/temp/e484cc96-2202-4c37-8493-e169844c0afb_back.jpg
Labels: feature

#27 FEAT: 위도,경도를 도로명주소로 만드는 기능 추가
  back/src/main/java/org/hotel/back/data/response/KaKaoAddressData.java
  back/src/main/java/org/hotel/back/service/api/KaKaoAPIService.java
  back/src/test/java/org/hotel/back/service/api/KaKaoAPIServiceTest.java
Labels: feature

#30 FEAT: Querydsl 추가
  back/build.gradle
  back/src/main/generated/org/hotel/back/domain/QBaseTimeEntity.java
  back/src/main/generated/org/hotel/back/domain/QBooking.java
  back/src/main/generated/org/hotel/back/domain/QHotel.java
  back/src/main/generated/org/hotel/back/domain/QHotelImage.java
  back/src/main/generated/org/hotel/back/domain/QMember.java
  back/src/main/generated/org/hotel/back/domain/QRating.java
  back/src/main/generated/org/hotel/back/domain/QReview.java
  back/src/main/generated/org/hotel/back/domain/QRoom.java
  back/src/main/generated/org/hotel/back/domain/QRoomImage.java
  back/src/main/java/org/hotel/back/config/MemberAuditorAware.java
  back/src/main/java/org/hotel/back/controller/HotelController.java
  back/src/main/java/org/hotel/back/controller/RoomController.java
  back/src/main/java/org/hotel/back/data/response/RoomDTO.java
  back/src/main/java/org/hotel/back/domain/Hotel.java
  back/src/main/java/org/hotel/back/repository/RoomRepository.java
  back/src/main/java/org/hotel/back/service/Impl/RoomServiceImpl.java
  back/src/main/java/org/hotel/back/service/RoomService.java
  back/src/main/resources/templates/room/room-detail.html
  back/src/main/resources/templates/room/room-list.html
  back/src/main/resources/templates/room/room-modify.html
  back/src/main/resources/templates/room/room-save.html
  back/temp/ebce91bf-aff9-4177-b8fb-f24d4e62db9e_back.jpg
Labels: feature

#37 Feat/hotel rating
  multi-module/.idea/compiler.xml
  multi-module/.idea/gradle.xml
  multi-module/.idea/inspectionProfiles/Project_Default.xml
  multi-module/.idea/jpa-buddy.xml
  multi-module/.idea/modules.xml
  multi-module/.idea/multi-module.iml
  multi-module/.idea/vcs.xml
  multi-module/.idea/workspace.xml
  multi-module/back/build.gradle
  multi-module/back/src/main/generated/org/hotel/back/domain/QHotel.java
  multi-module/back/src/main/generated/org/hotel/back/domain/QReview.java
  multi-module/back/src/main/java/org/hotel/back/config/MemberAuditorAware.java
  multi-module/back/src/main/java/org/hotel/back/controller/HotelController.java
  multi-module/back/src/main/java/org/hotel/back/data/request/HotelRequestDTO.java
  multi-module/back/src/main/java/org/hotel/back/data/request/ReviewRequestDTO.java
  multi-module/back/src/main/java/org/hotel/back/data/response/HotelListResponseDTO.java
  multi-module/back/src/main/java/org/hotel/back/data/response/HotelResponseDTO.java
  multi-module/back/src/main/java/org/hotel/back/data/response/ReviewResponseDTO.java
  multi-module/back/src/main/java/org/hotel/back/domain/Hotel.java
  multi-module/back/src/main/java/org/hotel/back/domain/Member.java
  multi-module/back/src/main/java/org/hotel/back/domain/Review.java
  multi-module/back/src/main/java/org/hotel/back/repository/HotelRepository.java
  multi-module/back/src/main/java/org/hotel/back/repository/ReviewRepository.java
  multi-module/back/src/main/java/org/hotel/back/service/HotelService.java
  multi-module/back/src/main/java/org/hotel/back/service/Impl/HotelServiceImpl.java
  multi-module/back/src/main/java/org/hotel/back/service/Impl/ReviewServiceImpl.java
  multi-module/back/src/main/java/org/hotel/back/service/ReviewService.java
  multi-module/back/src/main/resources/application.properties
  multi-module/back/src/main/resources/static/css/star.css
  multi-module/back/src/main/resources/static/css/styles.css
  multi-module/back/src/main/resources/templates/hotelDetail.html
  multi-module/back/src/main/resources/templates/hotelDetail2.html
  multi-module/back/src/main/resources/templates/hotelSave.html
  multi-module/back/src/main/resources/templates/hotelSearch.html
  multi-module/back/src/main/resources/templates/hotelimage.html
  multi-module/back/src/main/resources/templates/index.html
  multi-module/back/src/test/java/org/hotel/back/repository/HotelRepositoryTest.java
  multi-module/back/temp/0c5606e1-a013-4c0b-affe-8c05656f03ec_card_3.png
  multi-module/back/temp/1eda6a65-e061-4a4f-9ee9-745f5adacad5_card_2.png
  multi-module/back/temp/4b68821c-d761-4eaa-852a-8c0d191ee40e_제목을-입력해주세요_-001 (7).png
  multi-module/back/temp/7cf61c00-122b-4805-8a85-1790536a73b8_thumbnail (24).png
  multi-module/back/temp/8c20c755-1d61-4d00-8a59-eea9df6cdd68_card_back.png
  multi-module/back/temp/S_0c5606e1-a013-4c0b-affe-8c05656f03ec_card_3.png_card_3.png
  multi-module/back/temp/S_1eda6a65-e061-4a4f-9ee9-745f5adacad5_card_2.png_card_2.png
  multi-module/back/temp/S_7cf61c00-122b-4805-8a85-1790536a73b8_thumbnail (24).png
  multi-module/back/temp/S_8c20c755-1d61-4d00-8a59-eea9df6cdd68_card_back.png_card_back.png
  multi-module/back/temp/b164a891-6a1f-4d6f-9e72-3a1a2e5553dc_제목을-입력해주세요_-001 (6).png
  multi-module/back/temp/f049b8dd-afda-40c2-8a84-8f0872efff7d_IMG_7144.jpeg
Labels: Feat
